"""added table route

Revision ID: 96e2c016f660
Revises: 68c185979202
Create Date: 2024-04-28 04:10:12.261310

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '96e2c016f660'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE dyrtransportes.route MODIFY COLUMN price decimal(10,2) DEFAULT 0 NOT NULL;
        ALTER TABLE dyrtransportes.route MODIFY COLUMN payroll_price decimal(10,2) DEFAULT 0 NOT NULL;
        ALTER TABLE dyrtransportes.route MODIFY COLUMN deleted tinyint(1) DEFAULT false NOT NULL;
        ALTER TABLE dyrtransportes.route MODIFY COLUMN company_id varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.route MODIFY COLUMN modification_user varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;

        ALTER TABLE dyrtransportes.route_audit MODIFY COLUMN price decimal(10,2) DEFAULT 0 NOT NULL;
        ALTER TABLE dyrtransportes.route_audit MODIFY COLUMN payroll_price decimal(10,2) DEFAULT 0 NOT NULL;
        ALTER TABLE dyrtransportes.route_audit MODIFY COLUMN deleted tinyint(1) DEFAULT false NOT NULL;
        ALTER TABLE dyrtransportes.route_audit MODIFY COLUMN company_id varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.route_audit MODIFY COLUMN modification_user varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.route_audit MODIFY COLUMN audit_timestamp datetime DEFAULT CURRENT_TIMESTAMP NOT NULL;


        
        CREATE TRIGGER audit_route_insert AFTER INSERT ON route
        FOR EACH ROW
        BEGIN
            INSERT INTO route_audit (
                route_code, origin, destination, price, 
                payroll_price, deleted, company_id, modification_user
            ) VALUES (
                NEW.route_code, NEW.origin, NEW.destination, 
                NEW.price, NEW.payroll_price, NEW.deleted, 
                NEW.company_id, NEW.modification_user
            );
        END;

        CREATE TRIGGER audit_route_update AFTER UPDATE ON route
        FOR EACH ROW
        BEGIN
            INSERT INTO route_audit (
                route_code, origin, destination, price, 
                payroll_price, deleted, company_id, modification_user
            ) VALUES (
                NEW.route_code, NEW.origin, NEW.destination, 
                NEW.price, NEW.payroll_price, NEW.deleted, 
                NEW.company_id, NEW.modification_user
            );
        END;
        """
    )

    op.execute(
        """
        INSERT INTO dyrtransportes.route (origin, destination, price, payroll_price)
        SELECT origen, destino, precio, precio_liquidacion FROM dyrtransportes.precios
        """
    )

     # Get the maximum ID from the old table
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT COUNT(1) FROM dyrtransportes.precios"))
    result = res.fetchone()
     
    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        op.execute(f"ALTER TABLE dyrtransportes.route AUTO_INCREMENT = {result[0] + 1}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.route_audit;")
    op.execute("ALTER TABLE dyrtransportes.route_audit AUTO_INCREMENT = 1;")
    
    op.execute("DELETE FROM dyrtransportes.route;")
    op.execute("ALTER TABLE dyrtransportes.route AUTO_INCREMENT = 1;")
    op.execute("DROP TRIGGER IF EXISTS audit_route_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_route_update;")
    # ### end Alembic commands ###
