"""added table driver

Revision ID: d6f4a2249d99
Revises: da5e08d1bc88
Create Date: 2024-04-28 14:41:09.012198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f4a2249d99'
down_revision = 'da5e08d1bc88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE dyrtransportes.driver MODIFY COLUMN trailer_plate varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
        ALTER TABLE dyrtransportes.driver MODIFY COLUMN deleted tinyint(1) DEFAULT False NOT NULL;
        ALTER TABLE dyrtransportes.driver MODIFY COLUMN company_id varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.driver MODIFY COLUMN modification_user varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;

        ALTER TABLE dyrtransportes.driver_audit MODIFY COLUMN trailer_plate varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
        ALTER TABLE dyrtransportes.driver_audit MODIFY COLUMN deleted tinyint(1) DEFAULT False NOT NULL;
        ALTER TABLE dyrtransportes.driver_audit MODIFY COLUMN company_id varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.driver_audit MODIFY COLUMN modification_user varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.driver_audit MODIFY COLUMN audit_timestamp datetime DEFAULT CURRENT_TIMESTAMP NOT NULL;

        

        CREATE TRIGGER audit_driver_insert AFTER INSERT ON driver
        FOR EACH ROW
        BEGIN
            INSERT INTO driver_audit (
                driver_code, driver_name, truck_plate, trailer_plate, 
                deleted, company_id, modification_user
            ) VALUES (
                NEW.driver_code, NEW.driver_name, NEW.truck_plate, 
                NEW.trailer_plate, NEW.deleted, NEW.company_id, 
                NEW.modification_user
            );
        END;

        
        CREATE TRIGGER audit_driver_update AFTER UPDATE ON driver
        FOR EACH ROW
        BEGIN
            INSERT INTO driver_audit (
                driver_code, driver_name, truck_plate, trailer_plate, 
                deleted, company_id, modification_user
            ) VALUES (
                NEW.driver_code, NEW.driver_name, NEW.truck_plate, 
                NEW.trailer_plate, NEW.deleted, NEW.company_id, 
                NEW.modification_user
            );
        END;
        """
    )


    ##TODO: check more mispellings
    op.execute(
        """
        UPDATE dyrtransportes.cobranzas c
        SET c.chofer = 'Alcides Esteban Gamper'
        WHERE c.chofer = 'Alcides Esyteban Gamper';

        INSERT INTO dyrtransportes.driver (driver_name, truck_plate)
        SELECT 
            SUBSTRING_INDEX(p.palabra, '/', 1) as driver_name,
            SUBSTRING_INDEX(p.palabra, '/', -1) as truck_plate 
        FROM dyrtransportes.palabras p 
        WHERE p.id NOT IN
            (SELECT 
                palabras_a.id
            FROM
                (SELECT MAX(id) id, driver_name
                FROM
                    (SELECT
                        p.id,
                        SUBSTRING_INDEX(palabra, '/', 1) as driver_name,
                        SUBSTRING_INDEX(palabra, '/', -1) as truck_plate  
                    FROM dyrtransportes.palabras p
                    WHERE tipo = 'chofer/chapa' AND palabra != ''
                    ORDER BY id) temp_driver
                GROUP BY driver_name) palabras_a
            INNER JOIN dyrtransportes.palabras palabras_b ON
                palabras_a.id = palabras_b.id)
            AND p.palabra != ''
            AND p.tipo = 'chofer/chapa';

        DO SLEEP(1);
        """
    )

    op.execute(
        """    
        CREATE TABLE IF NOT EXISTS updated_data AS (
                SELECT
                    SUBSTRING_INDEX(p.palabra, '/', 1) driver_name,
                    SUBSTRING_INDEX(p.palabra, '/', -1) truck_plate 
                FROM dyrtransportes.palabras p 
                WHERE p.id IN
                        (SELECT 
                            palabras_a.id
                        FROM
                            (SELECT MAX(id) id, driver_name
                            FROM
                                (SELECT
                                    p.id,
                                    SUBSTRING_INDEX(palabra, '/', 1) as driver_name,
                                    SUBSTRING_INDEX(palabra, '/', -1) as truck_plate  
                                FROM dyrtransportes.palabras p
                                WHERE tipo = 'chofer/chapa' AND palabra != ''
                                ORDER BY id) temp_driver
                            GROUP BY driver_name) palabras_a
                        INNER JOIN dyrtransportes.palabras palabras_b ON
                            palabras_a.id = palabras_b.id)
                            
                    AND SUBSTRING_INDEX(p.palabra, '/', 1) IN (
                            SELECT d_hack.driver_name
                            FROM (SELECT * FROM dyrtransportes.driver d_copy) d_hack 
                        )
                        
                    AND p.palabra != ''
                    AND p.tipo = 'chofer/chapa'
        );

        DO SLEEP(1);
        """
    )

    op.execute(
        """
        UPDATE dyrtransportes.driver d
        JOIN dyrtransportes.updated_data ud ON d.driver_name  = ud.driver_name
        SET d.truck_plate  = ud.truck_plate;

        DO SLEEP(1);
        DROP TABLE updated_data;
        """
    )
    
    op.execute(
        """
        INSERT INTO dyrtransportes.driver (driver_name, truck_plate)
        SELECT 
            SUBSTRING_INDEX(p.palabra, '/', 1) driver_name,
            SUBSTRING_INDEX(p.palabra, '/', -1) truck_plate 
        FROM dyrtransportes.palabras p 
        WHERE p.id IN
                (SELECT 
                    palabras_a.id
                FROM
                    (SELECT MAX(id) id, driver_name
                    FROM
                        (SELECT
                            p.id,
                            SUBSTRING_INDEX(palabra, '/', 1) as driver_name,
                            SUBSTRING_INDEX(palabra, '/', -1) as truck_plate  
                        FROM dyrtransportes.palabras p
                        WHERE tipo = 'chofer/chapa' AND palabra != ''
                        ORDER BY id) temp_driver
                    GROUP BY driver_name) palabras_a
                INNER JOIN dyrtransportes.palabras palabras_b ON
                    palabras_a.id = palabras_b.id)
            AND SUBSTRING_INDEX(p.palabra, '/', 1) NOT IN (
                    SELECT d.driver_name
                    FROM dyrtransportes.driver d
                )
            AND p.palabra != ''
            AND p.tipo = 'chofer/chapa';

        DO SLEEP(1);
        """

        #TODO test
        # INSERT INTO dyrtransportes.driver (driver_name, truck_plate)
        # SELECT chofer, chapa 
        # FROM
        # (SELECT c.fecha_viaje, 
        #     c.chofer, 
        #     c.chapa, 
        #     d.driver_code,
        #     c.producto, 
        #     c.origen, 
        #     c.destino, 
        #     c.tiquet, 
        #     c.kilos_origen, 
        #     c.kilos_destino, 
        #     c.precio, 
        #     c.fecha_creacion
        # FROM dyrtransportes.cobranzas c
        # LEFT JOIN dyrtransportes.driver d ON
        #     d.driver_name = c.chofer 
        #     AND d.truck_plate = c.chapa) temp_shipment
        # WHERE temp_shipment.driver_code IS NULL;

    )

     # Get the maximum ID from the old table
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT COUNT(1) FROM dyrtransportes.driver"))
    result = res.fetchone()
     
    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        op.execute(f"ALTER TABLE dyrtransportes.driver AUTO_INCREMENT = {result[0] + 1}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.driver_audit;")
    op.execute("ALTER TABLE dyrtransportes.driver_audit AUTO_INCREMENT = 1;")
    
    op.execute("DELETE FROM dyrtransportes.driver;")
    op.execute("ALTER TABLE dyrtransportes.driver AUTO_INCREMENT = 1;")
    op.execute("DROP TRIGGER IF EXISTS audit_driver_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_driver_update;")
    # ### end Alembic commands ###