"""added table product

Revision ID: da5e08d1bc88
Revises: 96e2c016f660
Create Date: 2024-04-28 05:00:24.829947

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'da5e08d1bc88'
down_revision = '96e2c016f660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Copy data from the old table
    op.execute(
        """
        ALTER TABLE dyrtransportes.product MODIFY COLUMN deleted tinyint(1) DEFAULT False NOT NULL;
        ALTER TABLE dyrtransportes.product MODIFY COLUMN company_id varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.product MODIFY COLUMN modification_user varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;

        ALTER TABLE dyrtransportes.product_audit MODIFY COLUMN deleted tinyint(1) DEFAULT False NOT NULL;
        ALTER TABLE dyrtransportes.product_audit MODIFY COLUMN company_id varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.product_audit MODIFY COLUMN modification_user varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.product_audit MODIFY COLUMN audit_timestamp datetime DEFAULT CURRENT_TIMESTAMP NOT NULL;



        CREATE TRIGGER audit_product_insert AFTER INSERT ON product
        FOR EACH ROW
        BEGIN
            INSERT INTO product_audit (
                product_code, product_name, deleted, 
                company_id, modification_user
            ) VALUES (
                NEW.product_code, NEW.product_name, NEW.deleted, 
                NEW.company_id, NEW.modification_user
            );
        END;

        CREATE TRIGGER audit_product_update AFTER UPDATE ON product
        FOR EACH ROW
        BEGIN
            INSERT INTO product_audit (
                product_code, product_name, deleted, 
                company_id, modification_user
            ) VALUES (
                NEW.product_code, NEW.product_name, NEW.deleted, 
                NEW.company_id, NEW.modification_user
            );
        END;
        """
    )

    op.execute(
        """
        INSERT INTO dyrtransportes.product (product_name)
        SELECT palabra FROM dyrtransportes.palabras WHERE tipo = 'producto' AND palabra != ''
        """
    )

     # Get the maximum ID from the old table
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT COUNT(1) FROM dyrtransportes.palabras WHERE tipo = 'producto' AND palabra != ''"))
    result = res.fetchone()
     
    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        op.execute(f"ALTER TABLE dyrtransportes.product AUTO_INCREMENT = {result[0] + 1}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.product_audit;")
    op.execute("ALTER TABLE dyrtransportes.product_audit AUTO_INCREMENT = 1;")
    
    op.execute("DELETE FROM dyrtransportes.product;")
    op.execute("ALTER TABLE dyrtransportes.product AUTO_INCREMENT = 1;")
    op.execute("DROP TRIGGER IF EXISTS audit_product_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_product_update;")

    # ### end Alembic commands ###