"""added table shipment

Revision ID: 147c90063d23
Revises: 3562bc27785f
Create Date: 2024-04-28 18:23:49.349523

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '147c90063d23'
down_revision = '3562bc27785f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Copy data from the old table
    op.execute(
        """
        CREATE TRIGGER audit_shipment_insert AFTER INSERT ON shipment
        FOR EACH ROW
        BEGIN
            INSERT INTO shipment_audit (
                shipment_code, 
                shipment_date, 
                driver_code, 
                truck_plate, 
                product_code, 
                route_code, 
                price, 
                payroll_price, 
                dispatch_code, 
                receipt_code,
                origin_weight, 
                destination_weight, 
                shipment_payroll_code,
                driver_payroll_code, 
                deleted, 
                company_id, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.shipment_code, 
                NEW.shipment_date, 
                NEW.driver_code,
                NEW.truck_plate,
                NEW.product_code, 
                NEW.route_code, 
                NEW.price, 
                NEW.payroll_price, 
                NEW.dispatch_code, 
                NEW.receipt_code, 
                NEW.origin_weight, 
                NEW.destination_weight, 
                NEW.shipment_payroll_code, 
                NEW.driver_payroll_code, 
                NEW.deleted, 
                NEW.company_id, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;

        CREATE TRIGGER audit_shipment_update AFTER UPDATE ON shipment
        FOR EACH ROW
        BEGIN
            INSERT INTO shipment_audit (
                shipment_code, 
                shipment_date, 
                driver_code,
                truck_plate,
                product_code, 
                route_code, 
                price, 
                payroll_price, 
                dispatch_code, 
                receipt_code,
                origin_weight, 
                destination_weight, 
                shipment_payroll_code,
                driver_payroll_code, 
                deleted, 
                company_id, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.shipment_code, 
                NEW.shipment_date, 
                NEW.driver_code,
                NEW.truck_plate,
                NEW.product_code, 
                NEW.route_code, 
                NEW.price, 
                NEW.payroll_price, 
                NEW.dispatch_code, 
                NEW.receipt_code, 
                NEW.origin_weight, 
                NEW.destination_weight, 
                NEW.shipment_payroll_code, 
                NEW.driver_payroll_code, 
                NEW.deleted, 
                NEW.company_id, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;
        """
    )

    op.execute(
        """
        INSERT INTO dyrtransportes.liquidacion_viajes (id, precio_liquidacion, id_liquidacion)
        SELECT temp_cobranzas.id, temp_cobranzas.precio, l.id 
        FROM
            (SELECT 
                c.id, c.precio, c.chofer
            FROM dyrtransportes.cobranzas c
            LEFT JOIN dyrtransportes.liquidacion_viajes lv ON
                lv.id = c.id
            LEFT JOIN dyrtransportes.liquidaciones l ON
                lv.id_liquidacion = l.id
            WHERE 
                l.id IS NULL) temp_cobranzas
        INNER JOIN dyrtransportes.liquidaciones l ON
            l.chofer = temp_cobranzas.chofer AND l.fecha_liquidacion = CONVERT('2023-01-01', DATE);
        
            

        INSERT INTO dyrtransportes.shipment (
            shipment_date, 
            driver_code,
            truck_plate,
            product_code, 
            route_code, 
            price, 
            payroll_price,
            dispatch_code,
            receipt_code,
            origin_weight,
            destination_weight,
            shipment_payroll_code,
            driver_payroll_code,
            company_id,
            modification_user
        )
        SELECT
            c.fecha_viaje, 
            d.driver_code, 
            d.truck_plate, 
            p.product_code, 
            r.route_code, 
            c.precio, 
            IFNULL(lv.precio_liquidacion, 0) payroll_price, 
            '' dispatch_code, 
            CONVERT(c.tiquet, CHAR) receipt_code, 
            c.kilos_origen,
            c.kilos_destino,
            sp.payroll_code shipment_payroll_code,
            dp.payroll_code driver_payroll_code,
            'dyrtransportes',
            'dyrtransportes'
        FROM dyrtransportes.cobranzas c
        LEFT JOIN (
            SELECT a.driver_code, a.driver_name, a.truck_plate
            FROM dyrtransportes.driver a
            INNER JOIN (
                SELECT MAX(driver_code) driver_code, driver_name
                FROM dyrtransportes.driver
                GROUP BY driver_name
                ) b ON
                a.driver_code = b.driver_code 
                AND a.driver_name = b.driver_name) d ON
            d.driver_name = c.chofer
        LEFT JOIN dyrtransportes.product p ON
            p.product_name = producto
        LEFT JOIN dyrtransportes.route r ON
            r.origin = origen AND r.destination = destino
        LEFT JOIN dyrtransportes.liquidacion_viajes lv ON
            lv.id = c.id
        LEFT JOIN dyrtransportes.shipment_payroll sp ON
            sp.payroll_timestamp = CONVERT(c.fecha_creacion, DATETIME)
        LEFT JOIN dyrtransportes.liquidaciones l ON
            l.id = lv.id_liquidacion 
        LEFT JOIN dyrtransportes.driver_payroll dp ON
            dp.driver_code = d.driver_code 
        WHERE
            l.fecha_liquidacion = CONVERT(dp.payroll_timestamp, DATE);
        """
    )

    # Get the maximum ID from the old table

    conn = op.get_bind()
    res = conn.execute(
        sa.text("SELECT COUNT(1) FROM dyrtransportes.cobranzas"))
    result = res.fetchone()

    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        print(
            f"Setting AUTO_INCREMENT = {result[0] + 1}. Check if correct with table cobranzas")
        op.execute(
            f"ALTER TABLE dyrtransportes.shipment AUTO_INCREMENT = {result[0] + 1}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.shipment_audit;")
    op.execute("ALTER TABLE dyrtransportes.shipment_audit AUTO_INCREMENT = 1;")

    op.execute("DELETE FROM dyrtransportes.shipment;")
    op.execute("ALTER TABLE dyrtransportes.shipment AUTO_INCREMENT = 1;")
    op.execute("DROP TRIGGER IF EXISTS audit_shipment_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_shipment_update;")
    # ### end Alembic commands ###
