"""added table shipment

Revision ID: 147c90063d23
Revises: 3562bc27785f
Create Date: 2024-04-28 18:23:49.349523

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "147c90063d23"
down_revision = "3562bc27785f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Copy data from the old table

    op.execute(
        """
        INSERT INTO dyrtransportes.liquidacion_viajes (id, precio_liquidacion, id_liquidacion)
        SELECT temp_cobranzas.id, temp_cobranzas.precio, l.id 
        FROM
            (SELECT 
                c.id, c.precio, c.chofer
            FROM dyrtransportes.cobranzas c
            LEFT JOIN dyrtransportes.liquidacion_viajes lv ON
                lv.id = c.id
            LEFT JOIN dyrtransportes.liquidaciones l ON
                lv.id_liquidacion = l.id
            WHERE 
                l.id IS NULL) temp_cobranzas
        INNER JOIN dyrtransportes.liquidaciones l ON
            l.chofer = temp_cobranzas.chofer AND l.fecha_liquidacion = CONVERT('2023-01-01', DATE);
        
            

        INSERT INTO dyrtransportes.shipment (
            shipment_date,

            driver_name,
            truck_plate,
            trailer_plate,
            driver_code,

            product_code, 
            product_name,

            route_code, 
            origin,
            destination,
            price, 
            payroll_price,

            dispatch_code,
            receipt_code,
            origin_weight,
            destination_weight,
            shipment_payroll_code,
            driver_payroll_code,
            modification_user
        )
        SELECT
            TIMESTAMP(c.fecha_viaje, '03:00:00'),

            d.driver_name,
            d.truck_plate, 
            NULL,
            d.driver_code, 

            p.product_code, 
            p.product_name,

            r.route_code, 
            r.origin,
            r.destination,

            c.precio, 
            IFNULL(lv.precio_liquidacion, 0) payroll_price, 
            tiquet_remision dispatch_code, 
            CONVERT(c.tiquet, CHAR) receipt_code, 
            c.kilos_origen,
            c.kilos_destino,
            sp.payroll_code shipment_payroll_code,
            dp.payroll_code driver_payroll_code,
            'dyrtransportes'
        FROM dyrtransportes.cobranzas c
        LEFT JOIN (
            SELECT a.driver_code, a.driver_name, a.truck_plate
            FROM dyrtransportes.driver a
            INNER JOIN (
                SELECT MAX(driver_code) driver_code, driver_name
                FROM dyrtransportes.driver
                GROUP BY driver_name
                ) b ON
                a.driver_code = b.driver_code 
                AND a.driver_name = b.driver_name) d ON
            d.driver_name = c.chofer
        LEFT JOIN dyrtransportes.product p ON
            p.product_name = producto
        LEFT JOIN dyrtransportes.route r ON
            r.origin = origen AND r.destination = destino
        LEFT JOIN dyrtransportes.liquidacion_viajes lv ON
            lv.id = c.id
        LEFT JOIN dyrtransportes.shipment_payroll sp ON
            sp.payroll_timestamp = TIMESTAMP(c.fecha_creacion, '03:00:00')
        LEFT JOIN dyrtransportes.liquidaciones l ON
            l.id = lv.id_liquidacion 
        LEFT JOIN dyrtransportes.driver_payroll dp ON
            dp.driver_code = d.driver_code 
        WHERE
            l.fecha_liquidacion = CONVERT(dp.payroll_timestamp, DATE);
        """
    )

    # Get the maximum ID from the old table

    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT COUNT(1) FROM dyrtransportes.cobranzas"))
    result = res.fetchone()

    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        print(
            f"Setting AUTO_INCREMENT = {result[0] + 1}. Check if correct with table cobranzas"
        )
        op.execute(
            f"ALTER TABLE dyrtransportes.shipment AUTO_INCREMENT = {result[0] + 1}"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.shipment_audit;")
    op.execute("ALTER TABLE dyrtransportes.shipment_audit AUTO_INCREMENT = 1;")

    op.execute("DELETE FROM dyrtransportes.shipment;")
    op.execute("ALTER TABLE dyrtransportes.shipment AUTO_INCREMENT = 1;")
    # ### end Alembic commands ###
