"""added table driver_payroll

Revision ID: 3562bc27785f
Revises: e22d0d8dfb75
Create Date: 2024-04-28 16:01:25.667287

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3562bc27785f'
down_revision = 'e22d0d8dfb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Copy data from the old table
    op.execute(
        """
        ALTER TABLE dyrtransportes.driver_payroll MODIFY COLUMN paid tinyint(1) DEFAULT False NOT NULL;
        ALTER TABLE dyrtransportes.driver_payroll MODIFY COLUMN paid_timestamp datetime DEFAULT null NULL;
        ALTER TABLE dyrtransportes.driver_payroll MODIFY COLUMN deleted tinyint(1) DEFAULT False NOT NULL;
        ALTER TABLE dyrtransportes.driver_payroll MODIFY COLUMN company_id varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.driver_payroll MODIFY COLUMN modification_user varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        

        ALTER TABLE dyrtransportes.driver_payroll_audit MODIFY COLUMN paid tinyint(1) DEFAULT False NOT NULL;
        ALTER TABLE dyrtransportes.driver_payroll_audit MODIFY COLUMN paid_timestamp datetime DEFAULT null NULL;
        ALTER TABLE dyrtransportes.driver_payroll_audit MODIFY COLUMN deleted tinyint(1) DEFAULT False NOT NULL;
        ALTER TABLE dyrtransportes.driver_payroll_audit MODIFY COLUMN company_id varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.driver_payroll_audit MODIFY COLUMN modification_user varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.driver_payroll_audit MODIFY COLUMN audit_timestamp datetime DEFAULT CURRENT_TIMESTAMP NOT NULL;



        CREATE TRIGGER audit_driver_payroll_insert AFTER INSERT ON driver_payroll
        FOR EACH ROW
        BEGIN
            INSERT INTO driver_payroll_audit (
                payroll_code, creation_timestamp, driver_code, paid, 
                paid_timestamp, deleted, company_id, modification_user
            ) VALUES (
                NEW.payroll_code, NEW.creation_timestamp, 
                NEW.driver_code, NEW.paid, 
                NEW.paid_timestamp, NEW.deleted, 
                NEW.company_id, NEW.modification_user
            );
        END;

        CREATE TRIGGER audit_driver_payroll_update AFTER UPDATE ON driver_payroll
        FOR EACH ROW
        BEGIN
            INSERT INTO driver_payroll_audit (
                payroll_code, creation_timestamp, driver_code, paid, 
                paid_timestamp, deleted, company_id, modification_user
            ) VALUES (
                NEW.payroll_code, NEW.creation_timestamp, 
                NEW.driver_code, NEW.paid, 
                NEW.paid_timestamp, NEW.deleted, 
                NEW.company_id, NEW.modification_user
            );
        END;
        """
    )

    op.execute(
        """
        INSERT dyrtransportes.liquidaciones (chofer, fecha_liquidacion, pagado)
        SELECT 
            DISTINCT(c.chofer), 
            CONVERT('2023-01-01', DATE),
            TRUE pagado
        FROM dyrtransportes.cobranzas c
        LEFT JOIN dyrtransportes.liquidacion_viajes lv ON
            lv.id = c.id
        LEFT JOIN dyrtransportes.liquidaciones l ON
            lv.id_liquidacion = l.id
        WHERE 
            l.id IS NULL;

            
        INSERT INTO dyrtransportes.driver_payroll (
            driver_code, paid, 
            creation_timestamp,
            paid_timestamp)
        SELECT 
            temp_driver_table.driver_code, 
            l.pagado, 
            CONVERT(l.fecha_liquidacion, datetime), 
            IF(l.pagado, CONVERT(l.fecha_liquidacion, datetime), NULL) paid_timestamp
        FROM 
            dyrtransportes.liquidaciones l 
        LEFT JOIN 
            (SELECT 
                MAX(d.driver_code) driver_code, d.driver_name
            FROM 
                dyrtransportes.driver d 
            GROUP BY
                d.driver_name) temp_driver_table ON
            temp_driver_table.driver_name = l.chofer
        WHERE
            temp_driver_table.driver_code IS NOT NULL;
        """
    )

     # Get the maximum ID from the old table

    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT COUNT(1) FROM dyrtransportes.liquidaciones"))
    result = res.fetchone()
     
    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        print(f"Setting AUTO_INCREMENT = {result[0] + 1}. Check if correct with table liquidaciones")
        op.execute(f"ALTER TABLE dyrtransportes.driver_payroll AUTO_INCREMENT = {result[0] + 1}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.driver_payroll_audit;")
    op.execute("ALTER TABLE dyrtransportes.driver_payroll_audit AUTO_INCREMENT = 1;")
    
    op.execute("DELETE FROM dyrtransportes.driver_payroll;")
    op.execute("ALTER TABLE dyrtransportes.driver_payroll AUTO_INCREMENT = 1;")
    op.execute("DROP TRIGGER IF EXISTS audit_driver_payroll_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_driver_payroll_update;")
    # ### end Alembic commands ###