"""added table driver_payroll

Revision ID: 3562bc27785f
Revises: e22d0d8dfb75
Create Date: 2024-04-28 16:01:25.667287

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3562bc27785f"
down_revision = "e22d0d8dfb75"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Copy data from the old table

    op.execute(
        """
        INSERT dyrtransportes.liquidaciones (chofer, fecha_liquidacion, pagado)
        SELECT 
            DISTINCT(c.chofer), 
            CONVERT('2023-01-01', DATE),
            TRUE pagado
        FROM dyrtransportes.cobranzas c
        LEFT JOIN dyrtransportes.liquidacion_viajes lv ON
            lv.id = c.id
        LEFT JOIN dyrtransportes.liquidaciones l ON
            lv.id_liquidacion = l.id
        WHERE 
            l.id IS NULL;

            
        INSERT INTO dyrtransportes.driver_payroll (
            driver_code, paid, 
            payroll_timestamp,
            paid_timestamp,
            modification_user
        )
        SELECT 
            temp_driver_table.driver_code, 
            l.pagado, 
            TIMESTAMP(l.fecha_liquidacion, '03:00:00'), 
            IF(l.pagado, TIMESTAMP(l.fecha_liquidacion, '03:00:00'), NULL) paid_timestamp,
            'dyrtransportes'
        FROM 
            dyrtransportes.liquidaciones l 
        LEFT JOIN 
            (SELECT 
                MAX(d.driver_code) driver_code, d.driver_name
            FROM 
                dyrtransportes.driver d 
            GROUP BY
                d.driver_name) temp_driver_table ON
            temp_driver_table.driver_name = l.chofer
        WHERE
            temp_driver_table.driver_code IS NOT NULL;
        """
    )

    # Get the maximum ID from the old table

    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT COUNT(1) FROM dyrtransportes.liquidaciones"))
    result = res.fetchone()

    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        print(
            f"Setting AUTO_INCREMENT = {result[0] + 1}. Check if correct with table liquidaciones"
        )
        op.execute(
            f"ALTER TABLE dyrtransportes.driver_payroll AUTO_INCREMENT = {result[0] + 1}"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.driver_payroll_audit;")
    op.execute("ALTER TABLE dyrtransportes.driver_payroll_audit AUTO_INCREMENT = 1;")

    op.execute("DELETE FROM dyrtransportes.driver_payroll;")
    op.execute("ALTER TABLE dyrtransportes.driver_payroll AUTO_INCREMENT = 1;")
    # ### end Alembic commands ###
