"""added table route

Revision ID: 96e2c016f660
Revises: 68c185979202
Create Date: 2024-04-28 04:10:12.261310

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "96e2c016f660"
down_revision = None
branch_labels = None
depends_on = None

# Tables of the legacy database this data migration reads from
LEGACY_TABLES = ("precios",)


def upgrade():
    # This is a data migration from the legacy database. A fresh install has no
    # legacy tables, so there is nothing to migrate and the migration is skipped
    inspector = sa.inspect(op.get_bind())
    missing = [table for table in LEGACY_TABLES if not inspector.has_table(table)]
    if missing:
        print(f"Legacy tables {missing} not found, skipping data migration")
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO dyrtransportes.route (
            origin, 
            destination, 
            price, 
            payroll_price, 
            modification_user
        )
        SELECT 
            origen, 
            destino, 
            precio, 
            precio_liquidacion, 
            'dyrtransportes' 
        FROM dyrtransportes.precios
        """
    )

    # Get the maximum ID from the old table
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT COUNT(1) FROM dyrtransportes.precios"))
    result = res.fetchone()

    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        op.execute(f"ALTER TABLE dyrtransportes.route AUTO_INCREMENT = {result[0] + 1}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.route_audit;")
    op.execute("ALTER TABLE dyrtransportes.route_audit AUTO_INCREMENT = 1;")

    op.execute("DELETE FROM dyrtransportes.route;")
    op.execute("ALTER TABLE dyrtransportes.route AUTO_INCREMENT = 1;")
    # ### end Alembic commands ###
