"""added table route

Revision ID: 96e2c016f660
Revises: 68c185979202
Create Date: 2024-04-28 04:10:12.261310

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '96e2c016f660'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TRIGGER audit_route_insert AFTER INSERT ON route
        FOR EACH ROW
        BEGIN
            INSERT INTO route_audit (
                route_code, 
                origin, 
                destination, 
                price, 
                payroll_price, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.route_code, 
                NEW.origin, 
                NEW.destination, 
                NEW.price, 
                NEW.payroll_price, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;

        CREATE TRIGGER audit_route_update AFTER UPDATE ON route
        FOR EACH ROW
        BEGIN
            INSERT INTO route_audit (
                route_code, 
                origin, 
                destination, 
                price, 
                payroll_price, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.route_code, 
                NEW.origin, 
                NEW.destination, 
                NEW.price, 
                NEW.payroll_price, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;
        """
    )

    op.execute(
        """
        INSERT INTO dyrtransportes.route (
            origin, 
            destination, 
            price, 
            payroll_price, 
            modification_user
        )
        SELECT 
            origen, 
            destino, 
            precio, 
            precio_liquidacion, 
            'dyrtransportes' 
        FROM dyrtransportes.precios
        """
    )

    # Get the maximum ID from the old table
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT COUNT(1) FROM dyrtransportes.precios"))
    result = res.fetchone()

    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        op.execute(
            f"ALTER TABLE dyrtransportes.route AUTO_INCREMENT = {result[0] + 1}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.route_audit;")
    op.execute("ALTER TABLE dyrtransportes.route_audit AUTO_INCREMENT = 1;")

    op.execute("DELETE FROM dyrtransportes.route;")
    op.execute("ALTER TABLE dyrtransportes.route AUTO_INCREMENT = 1;")
    op.execute("DROP TRIGGER IF EXISTS audit_route_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_route_update;")
    # ### end Alembic commands ###
