"""added_triggers_old_models

Revision ID: be3b8045e548
Revises: f1261f65f342
Create Date: 2024-05-24 00:15:02.503110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3b8045e548'
down_revision: Union[str, None] = 'f1261f65f342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TRIGGER cobranzas_insert AFTER INSERT ON cobranzas
        FOR EACH ROW
        BEGIN
            DECLARE driver_code_var INT;
            DECLARE product_code_var INT;
            DECLARE route_code_var INT;
            DECLARE shipment_payroll_code_var INT;
            DECLARE driver_payroll_code_var INT;
            
            SELECT driver_code
            INTO driver_code_var
            FROM dyrtransportes.driver d
            WHERE d.driver_name = NEW.chofer
                AND d.truck_plate = NEW.chapa
                AND d.company_id = ''
                AND d.deleted = FALSE
            LIMIT 1;
                    
            SELECT product_code
            INTO product_code_var
            FROM dyrtransportes.product
            WHERE product_name = NEW.producto
                AND deleted = FALSE 
                AND company_id = ''
            LIMIT 1;
            
            SELECT route_code
            INTO route_code_var
            FROM dyrtransportes.route
            WHERE origin = NEW.origen
                AND destination = NEW.destino
                AND deleted = FALSE
                AND company_id = ''
            LIMIT 1;
            
            SELECT payroll_code
            INTO shipment_payroll_code_var
            FROM dyrtransportes.shipment_payroll
            WHERE deleted = FALSE
                AND company_id = ''
            ORDER BY 
                payroll_code DESC
            LIMIT 1;
            
            SELECT payroll_code
            INTO driver_payroll_code_var
            FROM dyrtransportes.driver_payroll
            WHERE 
                driver_code = driver_code_var
                AND deleted = FALSE
                AND company_id = ''
            LIMIT 1;
                

            INSERT INTO shipment (
                shipment_code,
                shipment_date,
                driver_code,
                product_code,
                route_code,
                price,
                payroll_price,
                dispatch_code,
                receipt_code,
                origin_weight,
                destination_weight,
                shipment_payroll_code,
                driver_payroll_code,
                deleted,
                company_id,
                modification_user)
            VALUES (
                NEW.id,
                NEW.fecha_viaje,
                driver_code_var,
                product_code_var,
                route_code_var,
                NEW.precio,
                0,
                '',
                NEW.tiquet,
                NEW.kilos_origen,
                NEW.kilos_destino,
                shipment_payroll_code_var,
                driver_payroll_code_var,
                FALSE,
                '',
                ''
            );
        END;
    """)

    op.execute("""
        CREATE TRIGGER cobranzas_update AFTER UPDATE ON cobranzas
        FOR EACH ROW
        BEGIN
            DECLARE driver_code_var INT;
            DECLARE product_code_var INT;
            DECLARE route_code_var INT;
            DECLARE shipment_payroll_code_var INT;
            DECLARE driver_payroll_code_var INT;
            
            SELECT driver_code
            INTO driver_code_var
            FROM dyrtransportes.driver d
            WHERE d.driver_name = NEW.chofer
                AND d.truck_plate = NEW.chapa
                AND d.company_id = ''
                AND d.deleted = FALSE
            LIMIT 1;
                    
            SELECT product_code
            INTO product_code_var
            FROM dyrtransportes.product
            WHERE product_name = NEW.producto
                AND deleted = FALSE 
                AND company_id = ''
            LIMIT 1;
            
            SELECT route_code
            INTO route_code_var
            FROM dyrtransportes.route
            WHERE origin = NEW.origen
                AND destination = NEW.destino
                AND deleted = FALSE
                AND company_id = ''
            LIMIT 1;
            
            SELECT payroll_code
            INTO shipment_payroll_code_var
            FROM dyrtransportes.shipment_payroll
            WHERE deleted = FALSE
                AND company_id = ''
            ORDER BY 
                payroll_code DESC
            LIMIT 1;
            
            SELECT payroll_code
            INTO driver_payroll_code_var
            FROM dyrtransportes.driver_payroll
            WHERE 
                driver_code = driver_code_var
                AND deleted = FALSE
                AND company_id = ''
            LIMIT 1;

            UPDATE shipment s
            SET
                s.shipment_date = NEW.fecha_viaje,
                s.driver_code = driver_code_var,
                s.product_code = product_code_var,
                s.route_code = route_code_var,
                s.price = NEW.precio,
                s.payroll_price = 0,
                s.dispatch_code = '',
                s.receipt_code = NEW.tiquet,
                s.origin_weight = NEW.kilos_origen,
                s.destination_weight = NEW.kilos_destino,
                s.shipment_payroll_code = shipment_payroll_code_var,
                s.driver_payroll_code = shipment_payroll_code_var,
                s.modification_user = ''
            WHERE
                s.shipment_code = NEW.id
            ;
        END;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS cobranzas_insert;")
    op.execute("DROP TRIGGER IF EXISTS cobranzas_update;")
    # ### end Alembic commands ###
