"""added table product

Revision ID: da5e08d1bc88
Revises: 96e2c016f660
Create Date: 2024-04-28 05:00:24.829947

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "da5e08d1bc88"
down_revision = "96e2c016f660"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Copy data from the old table

    op.execute(
        """
        INSERT INTO dyrtransportes.product (
            product_name,
            modification_user
        )
        SELECT 
            palabra,
            'dyrtransportes'  
        FROM dyrtransportes.palabras 
        WHERE 
            tipo = 'producto' 
            AND palabra != ''
        """
    )

    # Get the maximum ID from the old table
    conn = op.get_bind()
    res = conn.execute(
        sa.text(
            "SELECT COUNT(1) FROM dyrtransportes.palabras WHERE tipo = 'producto' AND palabra != ''"
        )
    )
    result = res.fetchone()

    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        op.execute(
            f"ALTER TABLE dyrtransportes.product AUTO_INCREMENT = {result[0] + 1}"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.product_audit;")
    op.execute("ALTER TABLE dyrtransportes.product_audit AUTO_INCREMENT = 1;")

    op.execute("DELETE FROM dyrtransportes.product;")
    op.execute("ALTER TABLE dyrtransportes.product AUTO_INCREMENT = 1;")
    # ### end Alembic commands ###
