"""added table shipment_expense

Revision ID: f1261f65f342
Revises: 147c90063d23
Create Date: 2024-04-29 02:19:29.192047

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f1261f65f342"
down_revision = "147c90063d23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Copy data from the old table

    op.execute(
        """     
        INSERT INTO dyrtransportes.shipment_expense (
            expense_date, 
            receipt, 
            amount,
            reason, 
            driver_payroll_code,
            modification_user
        )
        SELECT
            TIMESTAMP(lg.fecha, '03:00:00') expense_date,
            lg.boleta receipt,
            lg.importe amount,
            lg.razon reason,
            dp.payroll_code,
            'dyrtransportes'
        FROM dyrtransportes.liquidacion_gastos lg 
        INNER JOIN dyrtransportes.liquidaciones l ON
            l.id = lg.id_liquidacion
        LEFT JOIN dyrtransportes.driver d ON
            l.chofer = d.driver_name 
        INNER JOIN dyrtransportes.driver_payroll dp ON
            dp.driver_code = d.driver_code AND
            dp.payroll_timestamp = TIMESTAMP(l.fecha_liquidacion, '03:00:00')
        WHERE d.driver_code IS NOT NULL;
        """
    )

    # Get the maximum ID from the old table

    conn = op.get_bind()
    res = conn.execute(
        sa.text("SELECT COUNT(1) FROM dyrtransportes.liquidacion_gastos")
    )
    result = res.fetchone()

    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        print(f"Setting AUTO_INCREMENT = {result[0] + 1}. Check with LiquidacionGastos")
        op.execute(
            f"ALTER TABLE dyrtransportes.shipment_expense AUTO_INCREMENT = {result[0] + 1}"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.shipment_expense_audit;")
    op.execute("ALTER TABLE dyrtransportes.shipment_expense_audit AUTO_INCREMENT = 1;")

    op.execute("DELETE FROM dyrtransportes.shipment_expense;")
    op.execute("ALTER TABLE dyrtransportes.shipment_expense AUTO_INCREMENT = 1;")
    # ### end Alembic commands ###
