FROM python:3.10-slim

EXPOSE 5000

WORKDIR /app

COPY . .

RUN apt install pkg-config
# sudo apt-get install gcc libmysqlclient-dev python3-dev
RUN pip install -r requirements.txt

ENV FLASK_APP=flask_app.py

CMD ["flask", "run", "--host", "0.0.0.0"]