from .auth import auth_bp
from .route import route_bp
from .product import product_bp
from .driver import driver_bp
from .shipment import shipment_bp
from .shipment_payroll import shipment_payroll_bp
from .shipment_expense import shipment_expense_bp
from .driver_payroll import driver_payroll_bp
from .dinatran import dinatran_bp
from .statistics import statistics_bp
from .user_profile import user_profile_bp
