"""create_triggers

Revision ID: 8988cc02f61c
Revises: f1261f65f342
Create Date: 2025-03-29 21:59:44.392636

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8988cc02f61c"
down_revision: Union[str, None] = "f1261f65f342"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


### TODO: insert ALL existing entries
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Copy data from the old table

    ##TABLE ROUTE
    op.execute(
        """
        CREATE TRIGGER audit_route_insert AFTER INSERT ON route
        FOR EACH ROW
        BEGIN
            INSERT INTO route_audit (
                route_code, 
                origin, 
                destination, 
                price, 
                payroll_price, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.route_code, 
                NEW.origin, 
                NEW.destination, 
                NEW.price, 
                NEW.payroll_price, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;

        CREATE TRIGGER audit_route_update AFTER UPDATE ON route
        FOR EACH ROW
        BEGIN
            INSERT INTO route_audit (
                route_code, 
                origin, 
                destination, 
                price, 
                payroll_price, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.route_code, 
                NEW.origin, 
                NEW.destination, 
                NEW.price, 
                NEW.payroll_price, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;
        """
    )

    ## TABLE PRODUCT
    op.execute(
        """
        CREATE TRIGGER audit_product_insert AFTER INSERT ON product
        FOR EACH ROW
        BEGIN
            INSERT INTO product_audit (
                product_code, 
                product_name,
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.product_code, 
                NEW.product_name, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;

        CREATE TRIGGER audit_product_update AFTER UPDATE ON product
        FOR EACH ROW
        BEGIN
            INSERT INTO product_audit (
                product_code, 
                product_name, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.product_code, 
                NEW.product_name, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;
        """
    )

    ## TABLE DRIVER
    op.execute(
        """
        CREATE TRIGGER audit_driver_insert AFTER INSERT ON driver
        FOR EACH ROW
        BEGIN
            INSERT INTO driver_audit (
                driver_code, 
                driver_id, 
                driver_name, 
                driver_surname,
                truck_plate, 
                trailer_plate, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.driver_code, 
                NEW.driver_id, 
                NEW.driver_name, 
                NEW.driver_surname, 
                NEW.truck_plate, 
                NEW.trailer_plate, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;

        
        CREATE TRIGGER audit_driver_update AFTER UPDATE ON driver
        FOR EACH ROW
        BEGIN
            INSERT INTO driver_audit (
                driver_code, 
                driver_id, 
                driver_name, 
                driver_surname, 
                truck_plate, 
                trailer_plate, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.driver_code, 
                NEW.driver_id, 
                NEW.driver_name, 
                NEW.driver_surname,
                NEW.truck_plate, 
                NEW.trailer_plate, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;
        """
    )

    ##TABLE SHIPMENT
    op.execute(
        """
        CREATE TRIGGER audit_shipment_insert AFTER INSERT ON shipment
        FOR EACH ROW
        BEGIN
            INSERT INTO shipment_audit (
                shipment_code, 
                shipment_date,

                driver_name,
                truck_plate, 
                trailer_plate,
                driver_code, 

                product_code, 
                product_name,
                
                route_code, 
                origin,
                destination,
                price, 
                payroll_price, 

                dispatch_code, 
                receipt_code,
                origin_weight, 
                destination_weight, 
                shipment_payroll_code,
                driver_payroll_code, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.shipment_code, 
                NEW.shipment_date, 

                NEW.driver_name,
                NEW.truck_plate,
                NEW.trailer_plate,
                NEW.driver_code,

                NEW.product_code, 
                NEW.product_name,

                NEW.route_code, 
                NEW.origin,
                NEW.destination,
                NEW.price, 
                NEW.payroll_price, 

                NEW.dispatch_code, 
                NEW.receipt_code, 
                NEW.origin_weight, 
                NEW.destination_weight, 
                NEW.shipment_payroll_code, 
                NEW.driver_payroll_code, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;

        CREATE TRIGGER audit_shipment_update AFTER UPDATE ON shipment
        FOR EACH ROW
        BEGIN
            INSERT INTO shipment_audit (
                shipment_code, 
                shipment_date, 

                driver_name,
                truck_plate,
                trailer_plate,
                driver_code,

                product_code, 
                product_name,

                route_code, 
                origin,
                destination,
                price, 
                payroll_price, 

                dispatch_code, 
                receipt_code,
                origin_weight, 
                destination_weight, 
                shipment_payroll_code,
                driver_payroll_code, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.shipment_code, 
                NEW.shipment_date, 

                NEW.driver_name,
                NEW.truck_plate,
                NEW.trailer_plate,
                NEW.driver_code,

                NEW.product_code, 
                NEW.product_name,

                NEW.route_code, 
                NEW.origin,
                NEW.destination,
                NEW.price, 
                NEW.payroll_price, 

                NEW.dispatch_code, 
                NEW.receipt_code, 
                NEW.origin_weight, 
                NEW.destination_weight, 
                NEW.shipment_payroll_code, 
                NEW.driver_payroll_code, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;

        CREATE TRIGGER cascade_shipment_payroll_delete_shipments
        AFTER UPDATE ON shipment_payroll
        FOR EACH ROW
        BEGIN
            -- Only proceed if the deleted status has changed
            IF NEW.deleted != OLD.deleted THEN
                -- Update all shipments with the same shipment_payroll_code to match the deleted status
                UPDATE shipment
                SET deleted = NEW.deleted,
                    modification_timestamp = CURRENT_TIMESTAMP,
                    modification_user = NEW.modification_user
                WHERE shipment_payroll_code = NEW.payroll_code;
            END IF;
        END;
        """
    )

    ##TABLE SHIPMENT PAYROLL
    op.execute(
        """
        CREATE TRIGGER audit_shipment_payroll_insert AFTER INSERT ON shipment_payroll
        FOR EACH ROW
        BEGIN
            INSERT INTO shipment_payroll_audit (
                payroll_code, 
                collected, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.payroll_code, 
                NEW.collected, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;

        CREATE TRIGGER audit_shipment_payroll_update AFTER UPDATE ON shipment_payroll
        FOR EACH ROW
        BEGIN
            INSERT INTO shipment_payroll_audit (
                payroll_code, 
                collected, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.payroll_code, 
                NEW.collected, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;
        """
    )

    ##TABLE DRIVER PAYROLL
    op.execute(
        """
        CREATE TRIGGER audit_driver_payroll_insert AFTER INSERT ON driver_payroll
        FOR EACH ROW
        BEGIN
            INSERT INTO driver_payroll_audit (
                payroll_code, 
                payroll_timestamp, 
                driver_code, 
                paid, 
                paid_timestamp, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.payroll_code, 
                NEW.payroll_timestamp, 
                NEW.driver_code, 
                NEW.paid, 
                NEW.paid_timestamp, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;

        CREATE TRIGGER audit_driver_payroll_update AFTER UPDATE ON driver_payroll
        FOR EACH ROW
        BEGIN
            INSERT INTO driver_payroll_audit (
                payroll_code, 
                payroll_timestamp, 
                driver_code, 
                paid, 
                paid_timestamp, 
                deleted, 
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.payroll_code, 
                NEW.payroll_timestamp, 
                NEW.driver_code, 
                NEW.paid, 
                NEW.paid_timestamp, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;

        CREATE TRIGGER cascade_driver_payroll_delete_shipments_expenses
        AFTER UPDATE ON driver_payroll
        FOR EACH ROW
        BEGIN
            -- Only proceed if the deleted status has changed
            IF NEW.deleted != OLD.deleted THEN
                -- Update all shipments with the same driver_payroll_code to match the deleted status
                UPDATE shipment
                SET deleted = NEW.deleted,
                    modification_timestamp = CURRENT_TIMESTAMP,
                    modification_user = NEW.modification_user
                WHERE driver_payroll_code = NEW.payroll_code;

                UPDATE shipment_expense
                SET deleted = NEW.deleted,
                    modification_timestamp = CURRENT_TIMESTAMP,
                    modification_user = NEW.modification_user
                WHERE driver_payroll_code = NEW.payroll_code;
            END IF;
        END;
        """
    )

    ## TABLE SHIPMENT EXPENSE
    op.execute(
        """
        CREATE TRIGGER audit_shipment_expense_insert AFTER INSERT ON shipment_expense
        FOR EACH ROW
        BEGIN
            INSERT INTO shipment_expense_audit (
                expense_code, 
                expense_date, 
                receipt, 
                amount, 
                reason, 
                driver_payroll_code, 
                deleted,
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.expense_code,
                NEW.expense_date, 
                NEW.receipt, 
                NEW.amount, 
                NEW.reason, 
                NEW.driver_payroll_code, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;

        CREATE TRIGGER audit_shipment_expense_update AFTER UPDATE ON shipment_expense
        FOR EACH ROW
        BEGIN
            INSERT INTO shipment_expense_audit (
                expense_code, 
                expense_date, 
                receipt, 
                amount, 
                reason, 
                driver_payroll_code, 
                deleted,
                modification_user,
                modification_timestamp
            ) VALUES (
                NEW.expense_code, 
                NEW.expense_date, 
                NEW.receipt, 
                NEW.amount, 
                NEW.reason, 
                NEW.driver_payroll_code, 
                NEW.deleted, 
                NEW.modification_user,
                NEW.modification_timestamp
            );
        END;
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS audit_route_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_route_update;")

    op.execute("DROP TRIGGER IF EXISTS audit_product_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_product_update;")

    op.execute("DROP TRIGGER IF EXISTS audit_driver_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_driver_update;")

    op.execute("DROP TRIGGER IF EXISTS audit_shipment_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_shipment_update;")

    op.execute("DROP TRIGGER IF EXISTS audit_shipment_payroll_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_shipment_payroll_update;")

    op.execute("DROP TRIGGER IF EXISTS audit_driver_payroll_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_driver_payroll_update;")

    op.execute("DROP TRIGGER IF EXISTS audit_shipment_expense_insert;")
    op.execute("DROP TRIGGER IF EXISTS audit_shipment_expense_update;")
    # ### end Alembic commands ###
