# Steps (desde root del proyecto)
# 1. docker build -t python-flask-agent -f jenkins/Dockerfile.agent .
# 2. docker tag python-flask-agent:latest localhost:5000/dev/python-flask-agent:3.10.13
# 3. docker push localhost:5000/dev/python-flask-agent:3.10.13

FROM python:3.10.13

COPY flask/requirements.txt .

RUN pip install -r requirements.txt 
RUN pip install pylint

RUN groupadd --gid 1000 jenkins \
    && useradd --uid 1000 --gid jenkins --shell /bin/bash --create-home jenkins

# Add Docker's official GPG key:
RUN apt-get -y update && apt-get -y install ca-certificates curl gnupg && \
    apt-get clean -y
RUN install -m 0755 -d /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN chmod a+r /etc/apt/keyrings/docker.gpg

# Add the repository to Apt sources:
RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null

#Install Docker CLI
RUN apt-get -y update && apt-get -y install docker-ce-cli \
    inetutils-ping wget zip jq curl && \
    apt-get clean -y