"""added table shipment_payroll

Revision ID: e22d0d8dfb75
Revises: d6f4a2249d99
Create Date: 2024-04-28 15:02:16.062811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22d0d8dfb75'
down_revision = 'd6f4a2249d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE dyrtransportes.shipment_payroll MODIFY COLUMN collected tinyint(1) DEFAULT false NOT NULL;
        ALTER TABLE dyrtransportes.shipment_payroll MODIFY COLUMN deleted tinyint(1) DEFAULT false NOT NULL;
        ALTER TABLE dyrtransportes.shipment_payroll MODIFY COLUMN company_id varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.shipment_payroll MODIFY COLUMN modification_user varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;


        ALTER TABLE dyrtransportes.shipment_payroll_audit MODIFY COLUMN collected tinyint(1) DEFAULT false NOT NULL;
        ALTER TABLE dyrtransportes.shipment_payroll_audit MODIFY COLUMN deleted tinyint(1) DEFAULT false NOT NULL;
        ALTER TABLE dyrtransportes.shipment_payroll_audit MODIFY COLUMN company_id varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.shipment_payroll_audit MODIFY COLUMN modification_user varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL;
        ALTER TABLE dyrtransportes.shipment_payroll_audit MODIFY COLUMN audit_timestamp datetime DEFAULT CURRENT_TIMESTAMP NOT NULL;


        CREATE TRIGGER audit_shipment_payroll_insert AFTER INSERT ON shipment_payroll
        FOR EACH ROW
        BEGIN
            INSERT INTO shipment_payroll_audit (
                payroll_code, collected, deleted, 
                company_id, modification_user
            ) VALUES (
                NEW.payroll_code, NEW.collected, NEW.deleted, 
                NEW.company_id, NEW.modification_user
            );
        END;

        CREATE TRIGGER audit_shipment_payroll_update AFTER UPDATE ON shipment_payroll
        FOR EACH ROW
        BEGIN
            INSERT INTO shipment_payroll_audit (
                payroll_code, collected, deleted, 
                company_id, modification_user
            ) VALUES (
                NEW.payroll_code, NEW.collected, NEW.deleted, 
                NEW.company_id, NEW.modification_user
            );
        END;
        """
    )

    op.execute(
        """
        INSERT INTO dyrtransportes.shipment_payroll (creation_timestamp)
        SELECT fecha FROM dyrtransportes.planillas;
        """
    )

     # Get the maximum ID from the old table

    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT COUNT(1) FROM dyrtransportes.planillas"))
    result = res.fetchone()
     
    # Set the autoincrement start value (if supported by your database)
    if result is not None:
        op.execute(f"ALTER TABLE dyrtransportes.shipment_payroll AUTO_INCREMENT = {result[0] + 1}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM dyrtransportes.shipment_payroll_audit;")
    op.execute("ALTER TABLE dyrtransportes.shipment_payroll_audit AUTO_INCREMENT = 1;")
    
    op.execute("DELETE FROM dyrtransportes.shipment_payroll;")
    op.execute("ALTER TABLE dyrtransportes.shipment_payroll AUTO_INCREMENT = 1;")

    # ### end Alembic commands ###
